server:
  port: 8090
spring:
  application:
    name: utils-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blind_obstacle_detection?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: remote
    password: test

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    web-application-type: none
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
audience: # 代表这个JWT的接收对象,存入audience
  clientId: REDACTED # 密钥, 经过Base64加密, 可自行替换
  base64Secret: REDACTED # JWT的签发主体，存入issuer
  name: workhours
  expiresSecond: 72000000 # 过期时间，时间戳 120分钟
