server:
  port: 8082
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blind_obstacle_detection?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: remote
    password: REDACTED
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  configuration:
    map-underscore-to-camel-case: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
mybatis:
  configuration:
    map-underscore-to-camel-case: false
##  mapper-locations: classpath*:mapper/*.xml
#logging:
#  config: logback-timetable.xml
#  level:
#    cc:
#      yysy:
#        apigateway: info
