server:
  port: 8089
swagger:
  enabled: true
  base-package: cc.yysy.apidatasource
  version: V1.0
  description: 数据源接口
  terms-of-service-url: http://localhost:8009/doc.html
spring:
  application:
    name: api-datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blind_obstacle_detection?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: remote
    password: test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  rabbitmq:
    host: localhost
    port: 5672
    username: remote
    password: test
##  mapper-locations: classpath*:mapper/*.xml
#logging:
#  config: logback-timetable.xml
#  level:
#    cc:
#      yysy:
#        apigateway: info
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: minioadmin
  bucketName: obstacle-raw
